#!/usr/bin/zsh

local src=$1
local dst=$2

# Confirmation to prevent my dumb ass from making a mistake.
echo "This script copies $src to $dst.\n"
read -q "REPLY?Do you want to continue (y/N)? "
if ! [[ $REPLY =~ ^[Yy]$ ]]; then
    return 0
fi

# Run rsync from $src to $dst
rsync -avPR --delete $src $dst
