#!/usr/bin/zsh

_print_dotfiles_help() {
   print "** rsync_dotfiles Function Help **

rsync_dotfiles is the entrypoint to synchronize configs from the
dot-files directory to the home directory.

If you are looking for something new yourself, there are better
options for you. Look elsewhere.

rsync_options(<direction>, <config_opt>)

Possible <direction>:
 - g, get = Copies from dot-files to home.
 - p, put = Copies from home to dot-files.

Possible <config_opt>:
 - term = Terminal related configs; alacritty, oh-my-zsh, tmux, etc.
 - i3   = i3wm and required xfce configs
 - vim  = Classic Vim related configs
 - nvim = Neovim related configs

You can only pass a single config_opt to prevent you from being a
dumbass who screws up and overwrites stuff you don't want to.

Don't forget to do a gitdiff and then git commit and push."
}

_put_term() {
    local src="$HOME/./.alacritty.toml $HOME/./.tmux.conf $HOME/./.tmux $HOME/./.oh-my-zsh/themes/amorris.zsh-theme"
    local dst="$HOME/dot-files/"

    prompt_rsync $src $dst
}

_get_term() {
    local src="$HOME/./dot-files/.alacritty.toml $HOME/./dot-files/.tmux.conf $HOME/./dot-files/.tmux $HOME/./dot-files/.oh-my-zsh/themes/amorris.zsh-theme"
    local dst="$HOME/"

    prompt_rsync $src $dst
}

_put_i3() {
    local src="$HOME/./.config/i3/config $HOME/./.config/xfce4/xfconf/xfce-perchannel-xml"
    local dst="$HOME/dot-files/"

    prompt_rsync $src $dst
}

_get_i3() {
    local dst="$HOME/./dot-files/.config/i3/config $HOME/./dot-files/.config/xfce4/xfconf/xfce-perchannel-xml"
    local src="$HOME/"

    prompt_rsync $src $dst
}

_put_vim() {
    local src="$HOME/./.vimrc $HOME/./.gvimrc"
    local dst="$HOME/dot-files/"

    prompt_rsync $src $dst
}

_get_vim() {
    local src="$HOME/./dot-files/.vimrc $HOME/./dot-files/.gvimrc"
    local dst="$HOME/"

    prompt_rsync $src $dst
}

_put_nvim() {
    local src="$HOME/./.config/nvim/"
    local dst="$HOME/dot-files/.config/nvim/"

    prompt_rsync $src $dst
}

_get_nvim() {
    local src="$HOME/./dot-files/.config/nvim/"
    local dst="$HOME/.config/nvim/"

    prompt_rsync $src $dst
}

rsync_dotfiles() {
    # Check we have arguments.
    if (( $# < 2 )); then
        print "Not enough arguments." >&2
        _print_dotfiles_help
        return 1
    fi

    local valid_dirs=(g get p put)
    local valid_opts=(term i3 vim nvim)

    local direction=$1
    local config_opt=$2

    # Check our direction is valid
    if ! [[ ${valid_dirs[(ie)$direction]} -le ${#valid_dirs} ]]; then
        print "Invalid direction." >&2
        _print_dotfiles_help
        return 1
    fi

    # Check our config_opt is valid
    if ! [[ ${valid_opts[(ie)$config_opt]} -le ${#valid_opts} ]]; then
        print "Invalid option." >&2
        _print_dotfiles_help
        return 1
    fi

    if [[ "$config_opt" == "term" ]]; then
        if [[ "$direction" == "g" || "$direction" == "get" ]]; then
            _get_term
        elif [[ "$direction" == "p" || "$direction" == "put" ]]; then
            _put_term
        fi
    fi

    if [[ "$config_opt" == "i3" ]]; then
        if [[ "$direction" == "g" || "$direction" == "get" ]]; then
            _get_i3
        elif [[ "$direction" == "p" || "$direction" == "put" ]]; then
            _put_i3
        fi
    fi

    if [[ "$config_opt" == "vim" ]]; then
        if [[ "$direction" == "g" || "$direction" == "get" ]]; then
            _get_vim
        elif [[ "$direction" == "p" || "$direction" == "put" ]]; then
            _put_vim
        fi
    fi

    if [[ "$config_opt" == "nvim" ]]; then
        if [[ "$direction" == "g" || "$direction" == "get" ]]; then
            _get_nvim
        elif [[ "$direction" == "p" || "$direction" == "put" ]]; then
            _put_nvim
        fi
    fi
}

rsync_dotfiles "$@"
